// / <reference path="../jsx-runtime" />
/** @jsxImportSource ../jsx-runtime */
export const components = {
    canvas3D: "canvas3D",
    //animations
    booleanKeyframeTrack: "BooleanKeyFrameTrack",
    colorKeyframeTrack: "ColorKeyFrameTrack",
    numberKeyframeTrack: "NumberKeyFrameTrack",
    quaternionKeyframeTrack: "QuaternionKeyFrameTrack",
    stringKeyframeTrack: "StringKeyframeTrack",
    vectorKeyframeTrack: "VectorKeyFrameTrack",
    animationAction: "AnimationAction",
    animationClip: "AnimationClip",
    animationMixer: "AnimationMixer",
    animationObjectGroup: "AnimationObjectGroup",
    animationUtils: "AnimationUtils",
    keyframeTrack: "KeyframeTrack",
    propertyBinding: "PropertyBinding",
    propertyMixer: "PropertyMixer",
    //audio
    audio: "Audio",
    audioAnalyser: "AudioAnalyser",
    // audioContext: "AudioContext", namespace
    audioListener: "AudioListener",
    positionalAudio: "PositionalAudio",
    //Cameras
    arrayCamera: "ArrayCamera",
    camera: "Camera",
    cubeCamera: "CubeCamera",
    orthographicCamera: "OrthographicCamera",
    perspectiveCamera: "PerspectiveCamera",
    stereoCamera: "StereoCamera",
    //Core
    bufferAttribute: "BufferAttributes",
    bufferGeometry: "BufferGeometry",
    clock: "Clock",
    eventDispatcher: "EventDispatcher",
    glBufferAttribute: "GLBufferAttribute",
    instancedBufferAttribute: "InstancedBufferAttribute",
    instancedBufferGeometry: "InstancedBufferGeometry",
    instancedInterleavedBuffer: "InstancedInterleavedBuffer",
    interleavedBuffer: "InterleavedBuffer",
    interleavedBufferAttribute: "InterleavedBufferAttribute",
    layers: "Layers",
    object3D: "Object3D",
    raycaster: "Raycaster",
    renderTarget: "RenderTarget",
    uniform: "Uniform",
    uniformsGroup: "UniformsGroup",
    //Extras
    //Extras/Core
    curve: "Curve",
    curvePath: "CurvePath",
    // interpolations: "Interpolations", functions
    path: "Path",
    shape: "Shape",
    shapePath: "ShapePath",
    //Extras/Curves
    arcCurve: "ArcCurve",
    catmullRomCurve3: "CatmullRomCurve3",
    cubicBezierCurve: "CubicBezierCurve",
    cubicBezierCurve3: "CubicBezierCurve3",
    // curves: "Curves", IMPORTS
    ellipseCurve: "EllipseCurve",
    lineCurve: "LineCurve",
    lineCurve3: "LineCurve3",
    quadraticBezierCurve: "QuadraticBezierCurve",
    quadraticBezierCurve3: "QuadraticBezierCurve3",
    splineCurve: "SplineCurve",
    //Geometeries
    boxGeometry: "BoxGeometry",
    capsuleGeometry: "CapsuleGeometry",
    circleGeometry: "CircleGeometry",
    coneGeometry: "ConeGeometry",
    cylinderGeometry: "CylinderGeometry",
    dodecahedronGeometry: "DodecahedronGeometry",
    edgesGeometry: "EdgesGeometry",
    extrudeGeometry: "ExtrudeGeometry",
    // geometries: "Geometries", IMPORTS
    icosahedronGeometry: "IcosahedronGeometry",
    latheGeometry: "LatheGeometry",
    octahedronGeometry: "OctahedronGeometry",
    planeGeometry: "PlaneGeometry",
    polyhedronGeometry: "PolyhedronGeometry",
    ringGeometry: "RingGeometry",
    shapeGeometry: "ShapeGeometry",
    sphereGeometry: "SphereGeometry",
    tetrahedronGeometry: "TetrahedronGeometry",
    torusGeometry: "TorusGeometry",
    torusKnotGeometry: "TorusKnotGeometry",
    tubeGeometry: "TubeGeometry",
    wireframeGeometry: "WireframeGeometry",
    //Helpers
    arrowHelper: "ArrowHelper",
    axesHelper: "AxesHelper",
    box3Helper: "Box3Helper",
    boxHelper: "BoxHelper",
    cameraHelper: "CameraHelper",
    directionalLightHelper: "DirectionalLightHelper",
    gridHelper: "GridHelper",
    hemisphereLightHelper: "HemispherLightHelper",
    planeHelper: "PlaneHelper",
    pointLightHelper: "PointLightHelper",
    polarGridHelper: "PolarGridHelper",
    skeletonHelper: "SkeletonHelper",
    spotLightHelper: "SpotLightHelper",
    //Lights
    ambientLight: "AmbientLight",
    directionalLight: "DirectionalLight",
    hemisphereLight: "HemisphereLight",
    light: "Light",
    pointLight: "PointLight",
    rectAreaLight: "RectAreaLight",
    spotLight: "SpotLight",
    // Lights / Shadows
    lightShadow: "LightShadow",
    pointLightShadow: "PointLightShadow",
    directionalLightShadow: "DirectionalLightShadow",
    spotLightShadow: "SpotLightShadow",
    //Loader
    animationLoader: "AnimationLoader",
    audioLoader: "AudioLoader",
    bufferGeometryLoader: "BufferGeometryLoader",
    // cache: "Cache", namespace
    compressedTextureLoader: "CompressedTextureLoader",
    cubeTextureLoader: "CubeTextureLoader",
    dataTextureLoader: "DataTextureLoader",
    fileLoader: "FileLoader",
    imageBitmapLoader: "ImageBitmapLoader",
    imageLoader: "ImageLoader",
    loader: "Loader",
    // loaderUtils: "LoaderUtils", interface
    materialLoader: "MaterialLoader",
    objectLoader: "ObjectLoader",
    textureLoader: "TextureLoader",
    //Materials
    lineBasicMaterial: "LineBasicMaterial",
    lineDashedMaterial: "LineDashedMaterial",
    material: "Material",
    meshBasicMaterial: "MeshBasicMaterial",
    meshDepthMaterial: "MeshDepthMaterial",
    meshDistanceMaterial: "MeshDistanceMaterial",
    meshLambertMaterial: "MeshLambertMaterial",
    meshMatcapMaterial: "MeshMatcapMaterial",
    meshNormalMaterial: "MeshNormalMaterial",
    meshPhongMaterial: "MeshPhongMaterial",
    meshPhysicalMaterial: "MeshPhysicalMaterial",
    meshStandardMaterial: "MeshStandardMaterial",
    meshToonMaterial: "MeshToonMaterial",
    pointsMaterial: "PointsMaterial",
    rawShaderMaterial: "RawShaderMaterial",
    shaderMaterial: "ShaderMaterial",
    shadowMaterial: "ShadowMaterial",
    spriteMaterial: "SpriteMaterial",
    //Math
    box2: "Box2",
    box3: "Box3",
    color: "Color",
    cylindrical: "Cylindrical",
    euler: "Euler",
    frustum: "Frustum",
    interpolant: "Interpolant",
    line3: "Line3",
    mathUtils: "MathUtils",
    matrix3: "Matrix3",
    matrix4: "Matrix4",
    plane: "Plane",
    quaternion: "Quarternion",
    ray: "Ray",
    sphere: "Sphere",
    spherical: "Spherical",
    sphericalHarmonics3: "SphericalHarmonics3",
    triangle: "Triangle",
    vector2: "Vector2",
    vector3: "Vector3",
    vector4: "Vector4",
    //Math/Interpolants
    cubicInterpolant: "CubicInterpolant",
    discreteInterpolant: "DiscreteInterpolant",
    linearInterpolant: "LinearInterpolant",
    quaternionLinearInterpolant: "QuaternionLinearInterpolant",
    //Objects
    batchedMesh: "BatchedMesh",
    bone: "Bone",
    group: "Group",
    instancedMesh: "InstancedMesh",
    line: "Line",
    lineLoop: "LineLoop",
    lineSegments: "LineSegments",
    lod: "LOD",
    mesh: "Mesh",
    points: "Points",
    skeleton: "Skeleton",
    skinnedMesh: "SkinnedMesh",
    sprite: "Sprite",
    //Renderers
    webGLRenderer: "WebGLRenderer",
    webGLRenderTarget: "WebGLRenderTarget",
    webGL3DRenderTarget: "WebGL3DRenderTarget",
    webGLArrayRenderTarget: "WebGLArrayRenderTarget",
    webGLCubeRenderTarget: "WebGLCubeRenderTarget",
    // Renderers / Shaders
    // ShaderChunk
    // ShaderLib
    // UniformsLib
    // UniformsUtils
    //Renderers / WebXR
    webXRManager: "WebXRManager",
    //Scenes
    fog: "Fog",
    fogExp2: "FogExp2",
    scene: "Scene",
    //Textures
    canvasTexture: "CanvasTexture",
    compressedArrayTexture: "CompressedArrayTexture",
    compressedTexture: "CompressedTexture",
    cubeTexture: "CubeTexture",
    data3DTexture: "Data3DTexture",
    dataArrayTexture: "DataArrayTexture",
    dataTexture: "DataTexture",
    depthTexture: "DepthTexture",
    framebufferTexture: "FrameBufferTexture",
    source: "Source",
    texture: "Texture",
    videoTexture: "VideoTexture",
    // Addons
    // Animations
    cCDIKSolver: "CCDIKSolver",
    mMDAnimationHelper: "MMDAnimationHelper",
    mMDPhysics: "MMDPhysics",
    // Controls
    arcballControls: "ArcballControls",
    dragControls: "DragControls",
    firstPersonControls: "FirstPersonControls",
    flyControls: "FlyControls",
    mapControls: "MapControls",
    orbitControls: "OrbitControls",
    pointerLockControls: "PointerLockControls",
    trackballControls: "TrackballControls",
    transformControls: "TransformControls",
    // Geometries
    convexGeometry: "ConvexGeometry",
    decalGeometry: "DecalGeometry",
    parametricGeometry: "ParametricGeometry",
    textGeometry: "TextGeometry",
    sDFGeometryGenerator: "SDFGeometryGenerator",
    //Helpers
    lightProbeHelper: "LightProbeHelper",
    positionalAudioHelper: "PositionalAudioHelper",
    rectAreaLightHelper: "RectAreaLightHelper",
    vertexNormalsHelper: "VertexNormalsHelper",
    vertexTangentsHelper: "VertexTangentsHelper",
    // Lights
    // LightProbeGenerator //static
    // Loaders
    rhino3dmLoader: "Rhino3dmLoader",
    dracoLoader: "DRACOLoader",
    fontLoader: "FontLoader",
    gltfLoader: "GLTFLoader",
    ktx2Loader: "KTX2Loader",
    lDrawLoader: "LDrawLoader",
    lut3dlLoader: "LUT3dlLoader",
    lutCubeLoader: "LUTCubeLoader",
    mmdLoader: "MMDLoader",
    mtlLoader: "MTLLoader",
    objLoader: "OBJLoader",
    pcdLoader: "PCDLoader",
    pdbLoader: "PDBLoader",
    svgLoader: "SVGLoader",
    tgaLoader: "TGALoader",
    // Objects
    lensflare: "Lensflare",
    //Post-Processing
    effectComposer: "EffectComposer",
    exporters: "Exporters",
    dRACOExporter: "DRACOExporter",
    eXRExporter: "EXRExporter",
    gLTFExporter: "GLTFExporter",
    oBJExporter: "OBJExporter",
    pLYExporter: "PLYExporter",
    sTLExporter: "STLExporter",
    // Math
    // LookupTable
    lut: "Lut",
    meshSurfaceSampler: "MeshSurfaceSampler",
    obb: "OBB",
    // Misc
    timer: "Timer",
    // ConvexHull
    Face: "Face",
    HalfEdge: "HalfEdge",
    ConvexHull: "ConvexHull",
    VertexNode: "VertexNode",
    VertexList: "VertexList",
    // Renderers
    css2DRenderer: "CSS2DRenderer",
    css3DRenderer: "CSS3DRenderer",
    svgRenderer: "SVGRenderer",
    // Utils
    // BufferGeometryUtils
    // CameraUtils
    // SceneUtils
    // SkeletonUtils
    // WebXR
    xrEstimatedLight: "XREstimatedLight",
    // WebGLRenderer
    // WebGLProgram
};
