/*************************************************************************
* ADOBE CONFIDENTIAL
* ___________________
*
*  Copyright 2015 Adobe Systems Incorporated
*  All Rights Reserved.
*
* NOTICE:  All information contained herein is, and remains
* the property of Adobe Systems Incorporated and its suppliers,
* if any.  The intellectual and technical concepts contained
* herein are proprietary to Adobe Systems Incorporated and its
* suppliers and are protected by all applicable intellectual property laws,
* including trade secret and or copyright laws.
* Dissemination of this information or reproduction of this material
* is strictly forbidden unless prior written permission is obtained
* from Adobe Systems Incorporated.
**************************************************************************/
let e=null,t=null,n=null,o=null,r=null;async function i(...e){const t=await chrome.storage.local.get("hermesDebugMode"),n=t?.hermesDebugMode;"prod"!==await async function(){if(r)return r;const e=await chrome.runtime.sendMessage({main_op:"getEnvironment"});return r=e.environment,r}()&&n&&console.log(...e)}function a(){window.addEventListener("message",r=>{if(r.source===t){if(r.origin!==o)return void i("Rejected message from unauthorized parent origin:",r.origin,"Expected:",o);const{type:t,data:a,cdnUrl:s}=r.data;switch(t){case"SETUP_CDN_IFRAME":if(s){n=new URL(s).origin;const t=r.data.iframeConfig||{};i("Setting up CDN iframe with URL:",s,"and config:",t),function(t,n={}){if(e)try{const o={allowfullscreen:!1!==n.allowFullscreen?"true":"false",allow:n.allow||"clipboard-read; clipboard-write;",...n.attributes};Object.entries(o).forEach(([t,n])=>{null!=n&&e.setAttribute(t,n)});const r={width:n.iframeWidth||"100%",height:n.iframeHeight||"100%",border:n.iframeBorder||"none",overflow:n.iframeOverflow||"hidden",...n.iframeStyles};Object.entries(r).forEach(([t,n])=>{null!=n&&e.style.setProperty(t,n,"important")}),e.src=t,i("CDN iframe injected with URL:",t)}catch(e){i("Failed to inject CDN iframe",{error:e})}else i("CDN iframe element not found")}(s,t)}break;case"RELAY_TO_CDN":e&&e.contentWindow&&n?(i("Relaying message to CDN:",a),e.contentWindow.postMessage(a,n)):i("CDN iframe not ready for message relay or CDN origin not set");break;case"REMOVE_CDN_IFRAME":i("Removing CDN iframe"),e&&(e.src="",i("CDN iframe removed"))}}if(r.source===e?.contentWindow){if(n&&r.origin!==n)return void i("Rejected message from unauthorized CDN origin:",r.origin);if("DOWNLOAD_FILE_USING_CHROME_API"===r.data.type)return void function(e){const{buffer:t,fileName:n,fileType:o}=e,r=t.split(",")[1],a=atob(r),s=new ArrayBuffer(a.length),d=new Uint8Array(s);for(let e=0;e<a.length;e+=1)d[e]=a.charCodeAt(e);const c=new Blob([s],{type:o}),l=URL.createObjectURL(c);chrome.downloads.download({url:l,filename:n,conflictAction:"uniquify"},e=>{const t=n=>{n.id===e&&n.state&&"complete"===n.state.current&&(l&&URL.revokeObjectURL(l),chrome.downloads.onChanged.removeListener(t))};chrome.downloads.onChanged.addListener(t),chrome.runtime.lastError&&i(chrome.runtime.lastError)})}(r.data.payload);i("Relaying message from CDN to parent:",r.data),t.postMessage({type:"RELAY_FROM_CDN",data:r.data},o)}})}function s(){var n;n="Hermes: Hermes bridge initialized",chrome.runtime.sendMessage({main_op:"log-info",log:{message:n,executionSource:"hermes"}}),e=document.getElementById("cdn-iframe"),e.onload=()=>{const e=document.getElementById("loaderId");e&&e.remove()},t=window.parent,i("Hermes bridge initialized");const r=new URLSearchParams(window.location.search);o=r.get("parentOrigin"),a(),t.postMessage({type:"BRIDGE_READY"},o),i("BridgeReady message sent to parent with origin:",o)}"loading"===document.readyState?document.addEventListener("DOMContentLoaded",s):s();