import PMREMGenerator from 'three/src/renderers/common/extras/PMREMGenerator.js';
export { PMREMGenerator };
import { Three } from '../../../../lib/3/three';
import { consParams } from '../../../../lib/3/consParams';
import { objParams } from '../../../../lib/3/objParams';
import { defaults } from '../../../../lib/3/defaults';
Three.PMREMGenerator = PMREMGenerator;
consParams.pmremGenerator = ['renderer'];
objParams.pmremGenerator = [];
defaults.pMREMGenerator = {};
