/// <reference types='@types/three' />

// Explicitly re-export everything from woby to prevent tree-shaking
export {
    // Core
    $,
    $$,
    batch,
    context,
    createContext,
    useContext,
    createDirective,
    createElement,
    defaults,
    assign,
    make,
    clone,
    h,
    hmr,
    html,
    isBatching,
    isObservable,
    isObservableWritable,
    isServer,
    isStore,
    lazy,
    render,
    renderToString,
    resolve,
    store,
    template,
    tick,
    untrack,
    cloneElement,
    setRef,
    customElement,
    wrapCloneElement,
    SYMBOL_STACK,
    setPendingContextWrap,
    consumePendingContextWrap,

    // SSR
    ssr,
    WobyCustomElementsRegistry,
    wobyCustomElements,
    createDocument,

    // Utils
    castArray,
    castError,
    flatten,
    indexOf,
    isArray,
    isBoolean,
    isComponent,
    isError,
    isFalsy,
    isFunction,
    isClass,
    isFunctionReactive,
    isNil,
    isNode,
    isObject,
    isPrimitive,
    isPromise,
    isString,
    isSVG,
    isSVGElement,
    isTemplateAccessor,
    isTruthy,
    isVoidChild,
    mark,
    noop,
    once,
    fixBigInt,
    toArray,
    setProp,
    resolveArraysAndStatics,
    getSetters,
    FragmentUtils,

    // Constants
    DEBUGGER,
    Stack,
    callStack,
    SYMBOL_OBSERVABLE as ObservableSymbol,

    // JSX
    JSX,
} from 'woby'

// Re-export types from woby
export type {
    Observable,
    ObservableReadonly,
    ObservableOptions,
    BatchFunction,
    CallbackFunction,
    CleanupFunction,
    DisposeFunction,
    EffectFunction,
    ErrorFunction,
    EqualsFunction,
    MemoFunction,
    SelectorFunction,
    SuspenseFunction,
    TryCatchFunction,
    UntrackFunction,
    UpdateFunction,
    WithFunction,
    StoreOptions,
    CSSUnit,
    CSSLength,
    ArrayMaybe,
    Callback,
    Child,
    ChildWithMetadata,
    Classes,
    ComponentFunction,
    ComponentIntrinsicElement,
    ComponentNode,
    Component,
    ComponentsMap,
    ConstructorWith,
    ContextData,
    ContextProvider,
    Context,
    ContextWithDefault,
    DirectiveFunction,
    DirectiveProvider,
    DirectiveRef,
    DirectiveRegister,
    Directive,
    DirectiveData,
    DirectiveOptions,
    Disposer,
    Element,
    EventListener,
    Falsy,
    FN,
    FragmentUndefined,
    FragmentNode,
    FragmentFragment,
    FragmentNodes,
    FragmentFragments,
    FragmentMixed,
    FunctionMaybe,
    MemoOptions,
    LazyComponent,
    LazyFetcher,
    LazyResult,
    ObservableMaybe,
    PromiseMaybe,
    ObservableLike,
    Props,
    Ref,
    ResourceStaticPending,
    ResourceStaticRejected,
    ResourceStaticResolved,
    ResourceStatic,
    ResourceFunction,
    Resource,
    SuspenseData,
    TemplateActionPath,
    TemplateActionProxy,
    TemplateActionWithNodes,
    TemplateActionWithPaths,
    TemplateVariableProperties,
    TemplateVariableData,
    TemplateVariablesMap,
    Truthy,
    CSSProperties,
    Nullable,
    Unobservant,
    Observant,
    ElementAttributes,
    CustomElementChildren,
    StyleEncapsulationProps,
    SSRDocument,
} from 'woby'

// Export utils
export * from './utils'

export * from './three'
export * from './3/three'
export * from './jsx/runtime'
export * from './hooks'
export * from './components'
export * from '../three-types'
// export * from './examples/jsm'