export const components = {
    canvas3D: "canvas3D",
    //animations
    booleanKeyframeTrack: "BooleanKeyFrameTrack",
    colorKeyframeTrack: "ColorKeyFrameTrack",
    numberKeyframeTrack: "NumberKeyFrameTrack",
    quaternionKeyframeTrack: "QuaternionKeyFrameTrack",
    stringKeyframeTrack:"StringKeyframeTrack",
    vectorKeyframeTrack: "VectorKeyFrameTrack",
    animationAction: "AnimationAction",
    animationClip: "AnimationClip",
    animationMixer: "AnimationMixer",
    animationObjectGroup: "AnimationObjectGroup",
    animationUtils: "AnimationUtils",
    keyframeTrack: "KeyframeTrack",
    propertyBinding: "PropertyBinding",
    propertyMixer: "PropertyMixer",
    //audio
    audio: "Audio",
    audioAnalyser: "AudioAnalyser",
    // audioContext: "AudioContext", namespace
    audioListener: "AudioListener",
    positionalAudio: "PositionalAudio",
    //Cameras
    arrayCamera: "ArrayCamera",
    camera: "Camera",
    cubeCamera: "CubeCamera",
    orthographicCamera: "OrthographicCamera",
    perspectiveCamera: "PerspectiveCamera",
    stereoCamera: "StereoCamera",
    //core
    bufferAttribute: "BufferAttributes",
    bufferGeometry: "BufferGeometry",
    clock: "Clock",
    eventDispatcher: "EventDispatcher",
    glBufferAttribute: "GLBufferAttribute",
    instancedBufferAttribute: "InstancedBufferAttribute",
    instancedBufferGeometry: "InstancedBufferGeometry",
    instancedInterleavedBuffer: "InstancedInterleavedBuffer",
    interleavedBuffer: "InterleavedBuffer",
    interleavedBufferAttribute: "InterleavedBufferAttribute",
    layers: "Layers",
    object3D: "Object3D",
    raycaster: "Raycaster",
    renderTarget: "RenderTarget",
    uniform: "Uniform",
    uniformsGroup: "UniformsGroup",
    //extras
    curve: "Curve",
    curvePath: "CurvePath",
    // interpolations: "Interpolations", functions
    path: "Path",
    shape: "Shape",
    shapePath: "ShapePath",
    arcCurve: "ArcCurve",
    catmullRomCurve3: "CatmullRomCurve3",
    cubicBezierCurve: "CubicBezierCurve",
    cubicBezierCurve3: "CubicBezierCurve3",
    // curves: "Curves", IMPORTS
    ellipseCurve: "EllipseCurve",
    lineCurve: "LineCurve",
    lineCurve3: "LineCurve3",
    quadraticBezierCurve: "QuadraticBezierCurve",
    quadraticBezierCurve3: "QuadraticBezierCurve3",
    splineCurve: "SplineCurve",
    // dataUtils: "DataUtils", FUNCTIONS
    // earcut: "Earcut", FUNCTION
    // imageUtils: "ImageUtils", FUNCTIONS
    pMREMGenerator: "PMREMGenerator",
    // shapeUtils: "ShapeUtils", FUNCTIONS
    //geometeries
    boxGeometry: "BoxGeometry",
    capsuleGeometry: "CapsuleGeometry",
    circleGeometry: "CircleGeometry",
    coneGeometry: "ConeGeometry",
    cylinderGeometry: "CylinderGeometry",
    dodecahedronGeometry: "DodecahedronGeometry",
    edgesGeometry: "EdgesGeometry",
    extrudeGeometry: "ExtrudeGeometry",
    // geometries: "Geometries", IMPORTS
    icosahedronGeometry: "IcosahedronGeometry",
    latheGeometry: "LatheGeometry",
    octahedronGeometry: "OctahedronGeometry",
    planeGeometry: "PlaneGeometry",
    polyhedronGeometry: "PolyhedronGeometry",
    ringGeometry: "RingGeometry",
    shapeGeometry: "ShapeGeometry",
    sphereGeometry: "SphereGeometry",
    tetrahedronGeometry: "TetrahedronGeometry",
    torusGeometry: "TorusGeometry",
    torusKnotGeometry: "TorusKnotGeometry",
    tubeGeometry: "TubeGeometry",
    wireframeGeometry: "WireframeGeometry",
    //helpers
    arrowHelper: "ArrowHelper",
    axesHelper: "AxesHelper",
    box3Helper: "Box3Helper",
    boxHelper: "BoxHelper",
    cameraHelper: "CameraHelper",
    directionalLightHelper: "DirectionalLightHelper",
    gridHelper: "GridHelper",
    hemisphereLightHelper: "HemispherLightHelper",
    planeHelper: "PlaneHelper",
    pointLightHelper: "PointLightHelper",
    polarGridHelper: "PolarGridHelper",
    skeletonHelper: "SkeletonHelper",
    spotLightHelper: "SpotLightHelper",
    //lights
    ambientLight: "AmbientLight",
    ambientLightProbe: "AmbientLightProbe",
    directionalLight: "DirectionalLight",
    directionalLightShadow: "DirectionalLightShadow",
    hemisphereLight: "HemisphereLight",
    hemisphereLightProbe: "HemisphereLightProbe",
    light: "Light",
    lightProbe: "LightProbe",
    lightShadow: "LightShadow",
    pointLight: "PointLight",
    // pointLightShadow: "PointLightShadow", no constructor
    rectAreaLight: "RectAreaLight",
    spotLight: "SpotLight",
    // spotLightShadow: "SpotLightShadow", no constructor
    //loader
    animationLoader: "AnimationLoader",
    audioLoader: "AudioLoader",
    bufferGeometryLoader: "BufferGeometryLoader",
    // cache: "Cache", namespace
    compressedTextureLoader: "CompressedTextureLoader",
    cubeTextureLoader: "CubeTextureLoader",
    dataTextureLoader: "DataTextureLoader",
    fileLoader: "FileLoader",
    imageBitmapLoader: "ImageBitmapLoader",
    imageLoader: "ImageLoader",
    loader: "Loader",
    // loaderUtils: "LoaderUtils", interface
    loadingManager: "LoadingManager",
    materialLoader: "MaterialLoader",
    objectLoader: "ObjectLoader",
    textureLoader: "TextureLoader",
    //material
    lineBasicMaterial: "LineBasicMaterial",
    lineDashedMaterial: "LineDashedMaterial",
    material: "Material",
    // materials: "Materials", imports
    meshBasicMaterial: "MeshBasicMaterial",
    meshDepthMaterial: "MeshDepthMaterial",
    meshDistanceMaterial: "MeshDistanceMaterial",
    meshLambertMaterial: "MeshLambertMaterial",
    meshMatcapMaterial: "MeshMatcapMaterial",
    meshNormalMaterial: "MeshNormalMaterial",
    meshPhongMaterial: "MeshPhongMaterial",
    meshPhysicalMaterial: "MeshPhysicalMaterial",
    meshStandardMaterial: "MeshStandardMaterial",
    meshToonMaterial: "MeshToonMaterial",
    pointsMaterial: "PointsMaterial",
    rawShaderMaterial: "RawShaderMaterial",
    shaderMaterial: "ShaderMaterial",
    shadowMaterial: "ShadowMaterial",
    spriteMaterial: "SpriteMaterial",
    //math
    cubicInterpolant:"CubicInterpolant",
    discreteInterpolant:"DiscreteInterpolant",
    linearInterpolant:"LinearInterpolant",
    quaternionLinearInterpolant:"QuaternionLinearInterpolant",
    box2:"Box2",
    box3:"Box3",
    color:"Color",
    colorManagement:"ColorManagement",
    cylindrical:"Cylindrical",
    euler:"Euler",
    frustum:"Frustum",
    interpolant:"Interpolant",
    line3:"Line3",
    mathUtils:"MathUtils",
    matrix3:"Matrix3",
    matrix4:"Matrix4",
    plane:"Plane",
    quaternion:"Quarternion",
    ray:"Ray",
    sphere:"Sphere",
    spherical:"Spherical",
    sphericalHarmonics3:"SphericalHarmonics3",
    triangle:"Triangle",
    vector2:"Vector2",
    vector3:"Vector3",
    vector4:"Vector4",
    //objects
    bone: "Bone",
    group:"Group",
    instancedMesh:"InstancedMesh",
    line:"Line",
    lineLoop:"LineLoop",
    lineSegments:"LineSegments",
    LOD:"LOD",
    mesh:"Mesh",
    points:"Points",
    skeleton:"Skeleton",
    skinnedMesh:"SkinnedMesh",
    sprite:"Sprite",
    //renderers
    //shaders
    // shaderChunk:"ShaderChunk",
    // shaderLib:"ShaderLib",
    // uniformsLib:"UniformLib",
    // uniformsUtils:"UniformsUtils",
    //webgl
    webGLAttributes:"WebGLAttributes",
    webGLBindingStates:"WebGLBindingStates",
    webGLBufferRenderer:"WebGLBufferRenderer",
    webGLCapabilities:"WebGLCapabilities",
    webGLClipping:"WebGLClipping",
    webGlCubeMaps:"WebGLCubeMaps",
    webGLCubeUVMaps:"WebGLCubeUVMaps",
    webGLExtensions:"WebGLExtensions",
    webGLGeometries:"WebGLGeometries",
    webGLIndexedBufferRenderer:"WebGLIndexedBufferRenderer",
    webGLInfo:"WebGLInfo",
    webGLLights:"WebGLLights",
    webGLObjects:"WebGLObjects",
    webGLPrograms:"WebGLPrograms",
    webGlProperties:"WebGlProperties",
    webGLRenderLists:"WebGLRenderLists",
    webGLShaders:"WebGLShaders",
    webGlShadowMap:"WebGlShadowMap",
    webGLState:"WebGLState",
    webGLTextures:"WebGLTextures",
    webGLUniforms:"WebGLUniforms",
    // webGLUniformsGroups:"WebGLUniformsGroups", functions
    webGLUtils:"WebGLUtils",
    webXRController: "WebXRController",
    webXRManager:"WebXRManager",
    webGL1Renderer:"WebGL1Renderer",
    webGL3DRenderTarget:"WebGL3DRenderTarget",
    webGLArrayRenderTarget:"WebGLArrayRenderTarget",
    webGLCubeRenderTarget:"WebGLCubeRenderTarget",
    webGLMultipleRenderTarget:"WebGLMultipleRenderTarget",
    webGLRenderer:"WebGLRenderer",
    webGLRenderTarget:"WebGLRenderTarget",
    //scenes
    fog:"Fog",
    fogExp2:"FogExp2",
    scene:"Scene",
    //textures
    canvasTexture:"CanvasTexture",
    compressedArrayTexture:"CompressedArrayTexture",
    compressedTexture:"CompressedTexture",
    cubeTexture:"CubeTexture",
    data3DTexture:"Data3DTexture",
    dataArrayTexture:"DataArrayTexture",
    dataTexture:"DataTexture",
    depthTexture:"DepthTexture",
    framebufferTexture:"FrameBufferTexture",
    source:"Source",
    texture:"Texture",
    // types:"Types",
    videoTexture:"VideoTexture",
}
